version: '3.9'

services:

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: database
  my-docker-container:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  postgres_data:
